; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Tag Store"
#define MyAppNameCN "标签文件库"
#define MyAppPublisher "Antonidas"
#define MyAppURL "https://www.ymygc.com"
#define MyAppExeName "TagStore.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FA90E505-05C8-4514-AEA4-C243CDDAA0B2}
AppName={cm:AppName}
AppVersion={#GetFileVersion('.\bin\TagStore.exe')}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={cm:AppName} {#GetFileVersion('.\bin\TagStore.exe')}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=TagStoreSetup_{#GetFileVersion('.\bin\TagStore.exe')}
SetupIconFile=..\assets\icon.ico
SolidCompression=yes
WizardStyle=modern
; Self-update coordination: ask the running TagStore to close (via Windows
; Restart Manager) so its locked .exe can be replaced, and relaunch it after —
; this also makes the silent auto-update restart the app for the user.
CloseApplications=yes
RestartApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: .\bin\LICENSE.txt
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"; LicenseFile: .\bin\LICENSE_CN.txt

[CustomMessages]
english.AppName={#MyAppName}
chinesesimplified.AppName={#MyAppNameCN}

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: ".\bin\*.*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{cm:AppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{cm:AppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{cm:AppName}}"; Flags: nowait postinstall skipifsilent

[Code]
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  // Self-update safety net. CloseApplications (above) asks a running TagStore to
  // close gracefully via Restart Manager; if any instance ignores that request,
  // force-kill it here so the locked TagStore.exe can be replaced. taskkill
  // returning nonzero (nothing to kill) is expected and ignored.
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#MyAppExeName} /T',
       '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := '';
end;
